apiVersion: v1
kind: Service
metadata:
  name: ai_model_server
  namespace: {{ .Values.namespace }}
  labels:
    ai.service: ai_model_server
spec:
  selector:
    ai.service: ai_model_server
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
    - protocol: TCP
      port: 8501
      targetPort: 8501
