apiVersion: v1
kind: Service
metadata:
  name: smartid
  namespace: {{ .Values.namespace }}
  labels:
    ai.service: smartid
spec:
  selector:
    ai.service: smartid
  ports:
    - protocol: TCP
      port: 7444
      targetPort: 7444
